export interface UserRecord {
  id: string;
  name: string;
  email: string;
  avatarSrc?: string;
  status: "active" | "banned";
  trustScore: number;
  plan: "premium" | "free" | "trial";
  joined: string;
  lastActive: string;
  location: string;
  age: number;
  totalMatches: number;
  datesCompleted: number;
  photosCount: number;
  photos: string[];
}

export const usersDummyData: UserRecord[] = [
  {
    id: "user-1",
    name: "Sarah Chen",
    email: "sarah.chen@gmail.com",
    avatarSrc: "/assets/avatar.png",
    status: "active",
    trustScore: 94,
    plan: "premium",
    joined: "Jan 15, 2024",
    lastActive: "2 hours ago",
    location: "San Francisco, CA",
    age: 28,
    totalMatches: 12,
    datesCompleted: 3,
    photosCount: 4,
    photos: ["/assets/avatar.png", "/assets/avatar.png", "/assets/avatar.png", "/assets/avatar.png"],
  },
  {
    id: "user-2",
    name: "James Mitchell",
    email: "j.mitchell@outlook.com",
    status: "active",
    trustScore: 87,
    plan: "premium",
    joined: "Feb 3, 2024",
    lastActive: "1 day ago",
    location: "Oakland, CA",
    age: 31,
    totalMatches: 19,
    datesCompleted: 5,
    photosCount: 6,
    photos: ["/assets/avatar.png", "/assets/avatar.png"],
  },
  {
    id: "user-3",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    status: "active",
    trustScore: 72,
    plan: "free",
    joined: "Mar 10, 2024",
    lastActive: "3 hours ago",
    location: "San Jose, CA",
    age: 26,
    totalMatches: 8,
    datesCompleted: 2,
    photosCount: 5,
    photos: ["/assets/avatar.png", "/assets/avatar.png", "/assets/avatar.png"],
  },
  {
    id: "user-4",
    name: "Marcus Williams",
    email: "marcus.w@gmail.com",
    status: "banned",
    trustScore: 41,
    plan: "free",
    joined: "Nov 28, 2023",
    lastActive: "5 days ago",
    location: "Berkeley, CA",
    age: 29,
    totalMatches: 4,
    datesCompleted: 0,
    photosCount: 3,
    photos: ["/assets/avatar.png"],
  },
  {
    id: "user-5",
    name: "Emma Rodriguez",
    email: "emma.r@icloud.com",
    status: "active",
    trustScore: 96,
    plan: "premium",
    joined: "Dec 5, 2023",
    lastActive: "30 min ago",
    location: "San Francisco, CA",
    age: 27,
    totalMatches: 24,
    datesCompleted: 7,
    photosCount: 6,
    photos: ["/assets/avatar.png", "/assets/avatar.png", "/assets/avatar.png"],
  },
  {
    id: "user-6",
    name: "Tyler Brooks",
    email: "tbrooks@email.com",
    status: "active",
    trustScore: 65,
    plan: "free",
    joined: "Apr 2, 2024",
    lastActive: "2 days ago",
    location: "Palo Alto, CA",
    age: 30,
    totalMatches: 7,
    datesCompleted: 1,
    photosCount: 4,
    photos: ["/assets/avatar.png"],
  },
  {
    id: "user-7",
    name: "Aisha Johnson",
    email: "aisha.j@gmail.com",
    status: "active",
    trustScore: 88,
    plan: "premium",
    joined: "Jan 30, 2024",
    lastActive: "5 hours ago",
    location: "San Mateo, CA",
    age: 25,
    totalMatches: 15,
    datesCompleted: 4,
    photosCount: 5,
    photos: ["/assets/avatar.png", "/assets/avatar.png"],
  },
  {
    id: "user-8",
    name: "David Kim",
    email: "david.kim@outlook.com",
    status: "banned",
    trustScore: 12,
    plan: "free",
    joined: "Oct 15, 2023",
    lastActive: "20 days ago",
    location: "Fremont, CA",
    age: 33,
    totalMatches: 2,
    datesCompleted: 0,
    photosCount: 2,
    photos: ["/assets/avatar.png"],
  },
  {
    id: "user-9",
    name: "Nathan Foster",
    email: "nathan.foster@gmail.com",
    status: "active",
    trustScore: 82,
    plan: "free",
    joined: "Feb 18, 2024",
    lastActive: "1 hour ago",
    location: "San Francisco, CA",
    age: 28,
    totalMatches: 10,
    datesCompleted: 2,
    photosCount: 4,
    photos: ["/assets/avatar.png"],
  },
  {
    id: "user-10",
    name: "Maria Santos",
    email: "maria.santos@email.com",
    status: "active",
    trustScore: 91,
    plan: "premium",
    joined: "Mar 1, 2024",
    lastActive: "4 hours ago",
    location: "Oakland, CA",
    age: 27,
    totalMatches: 16,
    datesCompleted: 4,
    photosCount: 5,
    photos: ["/assets/avatar.png"],
  },
];
